### ISSUE TITLE
Remove Alchemy key from ENV

### ISSUE THREAD

**Issue by colthreepv** [Ithil-protocol/frontend#126]
Using Alchemy key on frontend exposes anyone to read it and consume the entire quota 😢

**Comment by colthreepv** [comment]
On this topic, when reading library documentation, most of them suggest to use an Alchemy key.
So seems standard operation to "publish" Alchemy RPC keys on your frontend

Any thoughts? @OxMarco  how does other frontends do this?

**Comment by OxMarco** [comment]
Apparently it's usually done, we can restrict the url to avoid getting the key stolen
