### ISSUE TITLE
Rainbowkit + wagmi - for connect modals and React hooks

### ISSUE THREAD

**Issue by colthreepv** [Ithil-protocol/frontend#127]
[Rainbowkit](https://www.rainbowkit.com/docs/installation) provides a simple and elegant connect modal, it forces use to use [wagmi](https://wagmi.sh/react/getting-started) tho.

Their interaction is really smooth: https://rainbowkit-demo.vercel.app/ 

A porting to these libraries would take 1~2 days of work, I would recommend it as it solves 2 issues: getting rid of uniswap old libraries, maintain a Ithil modal... and also gives a more modern react hook system

**Comment by OxMarco** [comment]
Ok, changed priority
