### ISSUE TITLE
Simplify css and styling

### ISSUE THREAD

**Issue by colthreepv** [Ithil-protocol/frontend#136]
At the moment styling is done via:
- tailwind.css
- twin.macro
- @emotion/css (overrides to styles)

Twin.Macro is nice but slows down compiling, and some things become a bit *magical* 🪄, like the very important `/** @jsxImportSource @emotion/react */` at the start of every `.tsx` file

## proposal
My proposal is to simplify, mostly using:
- tailwind.css
- styled-components when useful (reusable components)
- simple `styles` override when needed

Open to also use Chakra if a minimum number of components are deemed useful

**Comment by OxMarco** [comment]
Agreed on the proposal, styled components are the best option here, overrides are pretty rare
