### ISSUE TITLE
Remove hamburger menu from mobile

### ISSUE THREAD

**Issue by colthreepv** [Ithil-protocol/frontend#137]
In mobile the hamburger menu is useless. Those voices should be moved to the MobileModal

Mobile hamburger:  
![image](https://user-images.githubusercontent.com/2657230/220405845-bfab4000-929c-498c-9003-7a771ee98a40.png)

MobileModal:  
![image](https://user-images.githubusercontent.com/2657230/220405932-44d72769-ea81-48c3-ab79-f3637ad9199d.png)

**Comment by OxMarco** [comment]
Agreed, yet don't move them to the menu, just remove them. We can eventually add the list on the footer
